### ISSUE TITLE
VSIX extension fails to install

### ISSUE THREAD

**Issue by arcotek-ltd** [iswix-llc/iswix#8]
I have VS 2017 Enterprise (15.8.0).

I've tried installing with IsWiX.msi which didn't give me the IsWix project template.

I've also tried downloading and installing the [.vsix](https://marketplace.visualstudio.com/vsgallery/2eb3402e-ea6d-4dcd-8340-c88435e54ea9) extension using `VSIXInstaller.exe C:\Path\To\Votive2017.vsix` and that gives the error:
```
21/08/2018 16:57:01 - Microsoft VSIX Installer
21/08/2018 16:57:01 - -------------------------------------------
21/08/2018 16:57:01 - Initializing Install...
21/08/2018 16:57:01 - Extension Details...
21/08/2018 16:57:01 - 	Identifier      : WixToolset.VisualStudioExtension.Dev15
21/08/2018 16:57:01 - 	Name            : Wix Toolset Visual Studio 2017 Extension
21/08/2018 16:57:01 - 	Author          : .NET Foundation and contributors
21/08/2018 16:57:01 - 	Version         : 0.9.21.62588
21/08/2018 16:57:01 - 	Description     : Visual Studio integration for the WiX Toolset - the most powerful set of tools available to create your Windows installation experience.
21/08/2018 16:57:01 - 	Locale          : en-US
21/08/2018 16:57:01 - 	MoreInfoURL     : http://wixtoolset.org/
21/08/2018 16:57:01 - 	InstalledByMSI  : False
21/08/2018 16:57:01 - 	SupportedFrameworkVersionRange : [4.0,)
21/08/2018 16:57:01 - 
21/08/2018 16:57:01 - 	Supported Products : 
21/08/2018 16:57:01 - 		Microsoft.VisualStudio.Community
21/08/2018 16:57:01 - 			Version : [15.0,16.0)
21/08/2018 16:57:01 - 
21/08/2018 16:57:01 - 	References      : 
21/08/2018 16:57:01 - 
21/08/2018 16:57:01 - Searching for applicable products...
21/08/2018 16:57:01 - Found installed product - Global Location
21/08/2018 16:57:01 - Found installed product - ssms
21/08/2018 16:57:01 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

From this log, my guess is that the Enterprise version is not supported, however, [here](https://github.com/iswix-llc/iswix-tutorials), it says "Community edition or higher". Any ideas?

Many thanks

**Comment by iswix-llc** [comment]
IsWiX doesn't have a VSIX extension.  That's a WiX extension and an issue should be filed for it at https://github.com/wixtoolset/issues/issues or post a question in the wix-users list.

IsWiX does unfortunately build on top of Wix  like:

VSXXXX -> WiX 3.11 -> VSXXX Extension -> IsWiX

So you will need to fix that issue before IsWiX will fully work for you. (Project templates will be missing.)   The Tools | Launch IsWiX should be there.

Please post your resolution back here as a comment to help others who find this.

**Comment by RussellHaley** [comment]
Hi, 
I've been using ISWix with VS 2017 community edition for some time now. I installed the WIX toolset from the msi on their site (http://wixtoolset.org/releases/v3.11.1/stable), then installed ISWix. The ISWix templates are under the main Wix Toolset header when creating a new project.

**Comment by iswix-llc** [comment]
![image](https://user-images.githubusercontent.com/5349881/45326044-394d2600-b518-11e8-8b65-004206120483.png)

![image](https://user-images.githubusercontent.com/5349881/45326068-48cc6f00-b518-11e8-964c-ca3a52f514ad.png)

And there is VS2017 Enterprise with WiX / VS Extension and IsWiX properly installed.   Note along the bottom there are icons for VS2010, 2012, 2013, 2015 and 2017.  They are all working as expected.

In fact, we now have an inhouse CICD pipeline to this VM to make this type of testing easier.

![image](https://user-images.githubusercontent.com/5349881/45326192-9052fb00-b518-11e8-9485-257c0e26c6a9.png)
